name: Build, Test and Upload Artifact
description: Matrix releaser for Rust projects

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Print Runner Information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Architecture: ${{ runner.arch }}"
      shell: bash
    - name: Create Release
      run: ./release.sh
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        repository: ${{ github.repository }}
        server_url: ${{ github.server_url }}
        GIT_TOKEN: ${{ env.GIT_TOKEN }}
        WORKSPACE: ${{ github.workspace }}
