name: Build, Test and Upload Artifact
description: Matrix releaser for Rust projects

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Print Runner Information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Architecture: ${{ runner.arch }}"
      shell: bash
    - name: Set Path
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          chmod +x "${{ github.action_path }}\\release.sh"
          echo "release_sh=${{ github.action_path }}\\release.sh" >> $GITHUB_ENV
        else
          chmod +x "${{ github.action_path }}/release.sh"
          echo "release_sh=${{ github.action_path }}/release.sh" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Create Release
      run: "${{ env.release_sh }}"
      shell: bash
      env:
        repository: ${{ github.repository }}
        server_url: ${{ github.server_url }}
        GIT_TOKEN: ${{ env.GIT_TOKEN }}
